nelmio_cors:
    paths:
        '^/': ~
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['*']
        expose_headers: ['*']
        max_age: 3600